export enum Authority{
    ROLE_ADMIN = "ADMIN ",
    ROLE_CADASTRO = "CADASTRO",
    ROLE_CONFIG = "CONFIGURAÇÕES",
    ROLE_USER = "CUIDADOR",
    ROLE_CAD_PACIENTE = "CADASTRO DE PACIENTE",
    ROLE_CAD_RESPONSAVEL = "CADASTRO DE RESPONSAVEL",
    ROLE_CAD_AGENDA = "CADASTRO DE AGENDA",
    ROLE_CAD_USER = "CADASTRO DE USUÁRIOS"
}